#!/bin/sh
# Local RC Startup Script
#
# Install as /etc/init.d/rclocal
#
# chkconfig: 2345 99 00

### BEGIN INIT INFO
# Provides:          rclocal
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start rclocal scripts at boot time
# Description:       rclocal script facility
### END INIT INFO

PATH=/bin:/sbin:/usr/sbin:/usr/bin
export PATH

case "$1" in
start)
	echo "RC Local: start"
	touch /home/local/adm/rc.local.start.log
	rm -f /home/local/adm/rc.local.start.oldlog
	mv /home/local/adm/rc.local.start.log /home/local/adm/rc.local.start.oldlog

	#
	# Run all local rc start files
	#
	(
		for f in `echo /home/local/adm/rc-start/rc* | sort`; do
			if [ -s ${f} ]; then
				echo "RC Local: Starting $f" >&3
				echo ""
				echo "[------------------------------------------------"
				echo "[   Executing: $f"
				echo "[   Time: " `date`
				echo "[  "
				echo ""

				${f} 2>&1 </dev/null 3>&-
		
				echo ""
				echo "["
				echo "[   Completed: $f" 
				echo "[   Time: " `date`
				echo "[------------------------------------------------"
				echo ""
				echo "RC Local: Finished Starting $f" >&3
			fi
		done
	) 3>&1 1>/home/local/adm/rc.local.start.log 2>&1

	echo "RC Local: completed start"
	if [ -e "/var/lock/subsys" ]; then
		touch /var/lock/subsys/rclocal
	fi
	;;

stop)
	echo "RC Local: stop"
	touch /home/local/adm/rc.local.stop.log
	rm -f /home/local/adm/rc.local.stop.oldlog
	mv /home/local/adm/rc.local.stop.log /home/local/adm/rc.local.stop.oldlog

	#
	# Run all local rc stop files
	#
	(
		for f in `echo /home/local/adm/rc-stop/rc* | sort -r`; do
			if [ -s ${f} ]; then
				echo "RC Local: Stopping $f" >&3
				echo ""
				echo "[------------------------------------------------"
				echo "[   Executing: $f"
				echo "[   Time: " `date`
				echo "[  "
				echo ""

				${f} 2>&1 </dev/null 3>&-
		
				echo ""
				echo "["
				echo "[   Completed: $f" 
				echo "[   Time: " `date`
				echo "[------------------------------------------------"
				echo ""
				echo "RC Local: Finished Stopping $f" >&3
			fi
		done
	) 3>&1 1>/home/local/adm/rc.local.stop.log 2>&1

	echo "RC Local: completed stop"
	if [ -e "/var/lock/subsys" ]; then
		rm -f /var/lock/subsys/rclocal
	fi
	;;

restart)
	$0 stop
	$0 start
	;;

*) 	
	echo "RC Local: unknown option: $1"
	;;
esac

exit 0
